"""empty message

Revision ID: 7e21ef63751d
Revises: 04a72b9d4012
Create Date: 2026-02-18 10:29:48.772414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e21ef63751d'
down_revision = '04a72b9d4012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('classification', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cvss_vector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cvss_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remediation_complexity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('remediation_priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('remediation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poc', sa.Text(), nullable=True))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('poc')
        batch_op.drop_column('remediation')
        batch_op.drop_column('remediation_priority')
        batch_op.drop_column('remediation_complexity')
        batch_op.drop_column('cvss_score')
        batch_op.drop_column('cvss_vector')
        batch_op.drop_column('classification')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
