"""Add content and updated_at to Report

Revision ID: da8253bc6fc6
Revises: 357e30cc7ee3
Create Date: 2026-02-18 14:22:30.495767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8253bc6fc6'
down_revision = '357e30cc7ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
